version: '3.3'
services:
  mysql:
    image: mysql:8.0
    command: mysqld --user=root
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MYSQL_DATABASE: sablon
      MYSQL_USER: sablon
      MYSQL_PASSWORD: sablon
      MYSQL_ROOT_PASSWORD: sablon

  fcm_web:
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    container_name: fcm_web
    links:
      - "mysql:mysql"
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: Dockerfile-web
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    links:
      - "mysql:mysql"
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: sablon