version: '3.3'
services:
  fcm_web:
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    container_name: fcm_web
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: Dockerfile-web

